# Generated by Django 5.1.4 on 2025-01-05 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.ImageField(upload_to='image/')),
                ('format', models.CharField(blank=True, max_length=256, null=True)),
                ('filename', models.CharField(blank=True, max_length=256, null=True)),
                ('file_size', models.IntegerField(blank=True, default=0, null=True)),
                ('width', models.IntegerField(blank=True, default=0, null=True)),
                ('height', models.IntegerField(blank=True, default=0, null=True)),
                ('color_mode', models.CharField(blank=True, max_length=256, null=True)),
                ('dpi', models.CharField(blank=True, max_length=256, null=True)),
                ('metadata', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageConverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.ImageField(upload_to='convert/')),
                ('filename', models.CharField(blank=True, max_length=256, null=True)),
                ('format', models.CharField(blank=True, max_length=256, null=True)),
                ('file_size', models.IntegerField(blank=True, default=0, null=True)),
                ('width', models.IntegerField(blank=True, default=0, null=True)),
                ('height', models.IntegerField(blank=True, default=0, null=True)),
                ('color_mode', models.CharField(blank=True, max_length=256, null=True)),
                ('dpi', models.CharField(blank=True, max_length=256, null=True)),
                ('metadata', models.CharField(blank=True, max_length=256, null=True)),
                ('original_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='otimizimg.imageupload')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
