# Generated by Django 5.1.4 on 2025-01-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otimizimg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='optimized_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/optimized/'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='original_image',
            field=models.ImageField(upload_to='media/originals/'),
        ),
    ]
