# Generated by Django 5.1.4 on 2025-01-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otimizimg', '0002_alter_uploadedimage_optimized_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='optimized_format',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='optimized_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
