# Generated by Django 5.1.4 on 2025-01-03 23:35

import otimizimg.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otimizimg', '0003_uploadedimage_optimized_format_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedimage',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Imagem', 'verbose_name_plural': 'Imagens'},
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='height',
            field=models.IntegerField(default=0, editable=False, help_text='Altura da imagem em pixels'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, help_text='Última modificação'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='original_format',
            field=models.CharField(default=0, editable=False, help_text='Formato original da imagem', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='original_size',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Tamanho original em bytes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='width',
            field=models.IntegerField(default=0, editable=False, help_text='Largura da imagem em pixels'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='optimized_format',
            field=models.CharField(blank=True, choices=[('JPEG', 'JPEG'), ('PNG', 'PNG'), ('WEBP', 'WebP')], help_text='Formato da imagem otimizada', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='optimized_image',
            field=models.ImageField(blank=True, help_text='Versão otimizada da imagem', null=True, upload_to='optimized/'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='optimized_size',
            field=models.PositiveIntegerField(blank=True, help_text='Tamanho otimizado em bytes', null=True),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='original_image',
            field=models.ImageField(help_text='Imagem original para otimização', upload_to='originals/', validators=[otimizimg.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora do upload'),
        ),
    ]
